# _config.yml

# 站点基础配置
title: "高振源的个人主页"
description: "中南大学计算机科学学生 | AIGC & 机器学习爱好者"
baseurl: ""                            # 如果仓库名是 your-username.github.io，保持空字符串
url: "https://your-username.github.io" # 请替换为你的 GitHub Pages 地址

# 作者信息
author: "高振源"

# 主题（我们会自定义 default.html 来覆盖主题布局，但保留 Jekyll 内置的基础样式）
theme: jekyll-theme-cayman

# 插件（可自由增删）
plugins:
  - jekyll-sitemap

# Markdown 解析器
markdown: kramdown

# 指定要包含到发布中的静态文件夹
include:
  - assets/css/custom.css
future: true
