# _config.yml

# 站点基础配置
title: "高振源的个人主页"
description: "中南大学计算机科学学生 | AIGC & 机器学习爱好者"
baseurl: ""                             # GitHub Pages 仓库为 your-username.github.io 时保持空
url: "https://your-username.github.io"  # 替换为你的实际地址

# 作者信息
author: "高振源"

# 主题：Cayman，但我们会在 default.html 里加载自定义 CSS 覆盖部分样式
theme: jekyll-theme-cayman

# 插件列表（根据需要可增删）
plugins:
  - jekyll-sitemap

# 解析器
markdown: kramdown

# 允许将 custom.css 包含进构建
include:
  - assets/css/custom.css

# 如果需要在本地预览时渲染“未来”日期的文章，可临时设置：
# future: true
